import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className="font-sans">
        <header className="bg-black text-white p-4 flex justify-between">
          <h1 className="text-xl font-bold">Mi Tienda</h1>

          <nav className="flex gap-4">
            <a href="/" className="hover:text-gray-400">Inicio</a>
            <a href="/productos" className="hover:text-gray-400">Productos</a>
            <a href="/carrito" className="hover:text-gray-400">Carrito</a>
          </nav>
        </header>

        {children}

        <footer className="bg-black text-white text-center p-4 mt-10">
          © 2025 Mi tienda - Todos los derechos reservados
        </footer>
      </body>
    </html>
  );
}

/*export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/
